language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

script:
  - php vendor/bin/phpunit

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml